# Environment variables that must be set in Gitlab CI/CD Pipeline variables
# ASCII_DOCTOR_IMAGE
# CENTOS_IMAGE
# CI_COMMIT_TAG
# DOCKER_IMAGE
# DIND
# $CI_BUILD_TOKEN
# REGISTRY
# ORG

services:
  - ${DIND}

stages:
  - build
  - docs
#  - test

before_script:
  - mkdir -p $GOPATH/src/github.com/ngageoint
  - ln -s $(pwd) $GOPATH/src/github.com/ngageoint/seed-cli
  - cd $GOPATH/src/github.com/ngageoint/seed-cli

build:
  image: $SEED_COMMON:$CI_COMMIT_TAG
  stage: build
  artifacts:
    paths:
    - output/seed-darwin-amd64
    - output/seed-linux-amd64
    - output/seed-windows-amd64
  script:
    - ./build-cli.sh $CI_COMMIT_TAG
  only:
    - tags

# uncomment once we have an asciidoctor image with manpage on the high side
#docs:
#  image: $ASCII_DOCTOR_IMAGE
#  stage: docs
#  artifacts:
#    paths:
#    - /documents/output/seed-cli.adoc
#  script:
#    - asciidoctor -b manpage -D /documents/output seed-cli.adoc
#  only:
#    - tags

# uncomment once we have an image with go and docker working on the high side #147
#test:
#  stage: test
#  script:
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
#    - docker build --build-arg IMAGE=$CENTOS_IMAGE . -t $REGISTRY/$ORG/seed-silo:$CI_COMMIT_TAG
#    - docker push $REGISTRY/$ORG/seed-silo:$CI_COMMIT_TAG
#  only:
#    - master