sudo: required

language: go

services:
  - docker

install:
  - vendor/go-bindata-Linux -pkg assets -o assets/assets.go ./schema/*
  - go get github.com/ngageoint/seed-common/...
  - docker pull rochdev/alpine-asciidoctor:mini

script:
  - echo "Validating formatting with gofmt..."
  - gofmt -l . | grep -v assets\.go | if [[ $(wc -l | sed 's/ //g')>0 ]] ; then echo gofmt should be run on $(gofmt -l . | grep -v assets\.go); exit 1 ;fi
  - ./build-cli.sh ${TRAVIS_TAG}
  - docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/auth:/auth -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd -e REGISTRY_STORAGE_DELETE_ENABLED=true registry:2
  - go test ./...
  - docker run -v $TRAVIS_BUILD_DIR/readme.adoc:/documents/readme.adoc -v $TRAVIS_BUILD_DIR/seed-cli.adoc:/documents/seed-cli.adoc --name=seed-man rochdev/alpine-asciidoctor:mini asciidoctor -b manpage -D /documents/output seed-cli.adoc

deploy:
  # Deployment that pushes GitHub releases of software on tag
  - provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file: output/*
    skip_cleanup: true
    on:
      tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/10070a680400c55e3baa
    on_success: change
    on_failure: always
    on_start: never
